' Gambas module file

Public Sub copia_dir(path_origen As String, path_destino As String, Optional tipo As String)

    Dim arDir As String[]
    Dim arFile As String[]
    Dim nombredir, nombrefile As String

    If Not tipo Then tipo = "*"
    If Not Exist(path_destino) Then
        Mkdir path_destino
    Endif
    arfile = Dir(path_origen, tipo, gb.file)  'extraemos los ficheros
    For Each nombrefile In arfile  'los copiamos
        If Not Exist(path_destino &/ nombrefile) Then Copy path_origen &/ nombrefile To path_destino &/ nombrefile
    Next
    ardir = Dir(path_origen, "*", gb.Directory)
    For Each nombredir In arDir 'extraemos los subdirectorios
        If Not Exist(path_destino &/ nombredir) Then copia_dir(path_origen &/ nombredir, path_destino &/ nombredir) 'usamos la recursividad
    Next

End